### ISSUE TITLE
variable 'data'  duplcated naming cause _getAll() function dosen't work.

### ISSUE THREAD

**Issue by charleybin** [chuyentt/localstore#21]
bug code is:
![image](https://user-images.githubusercontent.com/1089391/206965202-101c7375-b55f-4f41-8ac0-7d05f5fb9494.png)
Description:
the 'data' variable  being declared twice, this may cause first veriable be ignored always.

suggested fix code is:
![image](https://user-images.githubusercontent.com/1089391/206965470-bc1cc123-aacc-4a6f-be9c-4b90ac36b10f.png)

NOTE:
the same bug existed both in utils/io.dart & utils/html.dart,  the same function & the same bug, function named '_getAll' , please take a look.

**Comment by chuyentt** [comment]
Thanks! I've released 1.3.2

**Comment by charleybin** [comment]
please check it again, I just pulled 1.3.2, codes are still old one.
