### ISSUE TITLE
Deletion not working

### ISSUE THREAD

**Issue by Jamminroot** [chuyentt/localstore#7]
Library puts contents of collections to `C:\Users\jamminroot\Documents\tags\igi9wjhos`, read works just fine, but deletion refers to

`C:\Users\jamminroot\Documents\tags\\tags\igi9wjhos` (note double "tags" and double slash), and ` if (_file.existsSync()) {` fails to evaluate, thus deletion is not working.

**Comment by Jamminroot** [comment]
Also, root directory for App-specific files to be users's Documents is probably not quite the way to go

**Comment by Jamminroot** [comment]
getApplicationSupportDirectory() should make more sense

**Comment by Jamminroot** [comment]
Also, I think it should be like this (`document_ref.dart`), otherwise we end up with duplicated collection name in path:
```dart
  /// A string representing the path of the referenced document (relative to the
  /// root of the database).
  String get path => id;
```

**Comment by Jamminroot** [comment]
I did fix that in my "fork", it's not too hard. I can dig for diff if you need that

**Comment by chuyentt** [comment]
> I did fix that in my "fork", it's not too hard. I can dig for diff if you need that

Hi Jamminroot,
Please PR and fix it.
I'm sorry, I'm very busy right now, I already know that and will look into it when I'm free.

**Comment by Jamminroot** [comment]
@sharokh1 can you have a look at PR I've submitted and check if the fix is valid? I don't really have SDK at my current machine (yet), so can't verify myself.

**Comment by Jamminroot** [comment]
Glad to see my PR merged 👍 I'm closing the issue then.
